# Generated by Django 4.2.7 on 2026-02-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('public_key', models.TextField(blank=True, help_text='secp256k1 public key (hexadecimal)', null=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('enrollment_status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('revoked', 'Révoqué'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('last_authentication', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zk_auth_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ZK Auth User',
                'verbose_name_plural': 'ZK Auth Users',
                'db_table': 'zk_auth_users',
            },
        ),
        migrations.CreateModel(
            name='TokenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.zkauthuser')),
            ],
            options={
                'db_table': 'token_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment_a_location', models.CharField(default='google_drive', max_length=255)),
                ('fragment_b_location', models.CharField(default='zk_auth_cloud', max_length=255)),
                ('fragment_b_encrypted', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('backup_email_sent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_backup', to='authentication.zkauthuser')),
            ],
            options={
                'db_table': 'key_backups',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='authentication.zkauthuser')),
            ],
            options={
                'db_table': 'device_info',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked'), ('expired', 'Challenge Expired'), ('revoked', 'Session Revoked')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('challenge_used', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to='authentication.zkauthuser')),
            ],
            options={
                'db_table': 'authentication_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='authentication.zkauthuser')),
            ],
            options={
                'db_table': 'authentication_challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='zkauthuser',
            index=models.Index(fields=['phone'], name='zk_auth_use_phone_3261df_idx'),
        ),
        migrations.AddIndex(
            model_name='zkauthuser',
            index=models.Index(fields=['is_enrolled'], name='zk_auth_use_is_enro_9d30da_idx'),
        ),
        migrations.AddIndex(
            model_name='zkauthuser',
            index=models.Index(fields=['user'], name='zk_auth_use_user_id_fcc220_idx'),
        ),
        migrations.AddIndex(
            model_name='zkauthuser',
            index=models.Index(fields=['enrollment_status'], name='zk_auth_use_enrollm_2ca05e_idx'),
        ),
        migrations.AddIndex(
            model_name='tokensession',
            index=models.Index(fields=['token'], name='token_sessi_token_42a3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='tokensession',
            index=models.Index(fields=['user', 'is_revoked'], name='token_sessi_user_id_9fe0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tokensession',
            index=models.Index(fields=['expires_at'], name='token_sessi_expires_2e2630_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['user', 'is_active'], name='device_info_user_id_7a67fe_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['device_id'], name='device_info_device__718b26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinfo',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='authenticationlog',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_7946d5_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationlog',
            index=models.Index(fields=['status'], name='authenticat_status_8b488e_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationlog',
            index=models.Index(fields=['timestamp'], name='authenticat_timesta_b1e7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationlog',
            index=models.Index(fields=['username'], name='authenticat_usernam_0b413a_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationchallenge',
            index=models.Index(fields=['challenge'], name='authenticat_challen_7f5ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationchallenge',
            index=models.Index(fields=['user', 'used'], name='authenticat_user_id_3654d8_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationchallenge',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_b0323e_idx'),
        ),
    ]
