# Generated by Django 4.2.7 on 2026-02-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_zkauthuser_phone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zkauthuser',
            name='zk_auth_use_phone_3261df_idx',
        ),
        migrations.RemoveField(
            model_name='zkauthuser',
            name='phone',
        ),
    ]
